import 'dart:math' as math;

import 'package:meta/meta.dart' show immutable;

import '../enums/ventilation_enums.dart';

// ═══════════════════════════════════════════════════════════════════════════
// 1. VentParams — all operator-settable ventilator parameters
// ═══════════════════════════════════════════════════════════════════════════

/// Immutable snapshot of ventilator knob settings and patient lung mechanics.
///
/// The ventilator mode determines which fields are actively used:
/// - **VCV**: [vt] and flow (derived from [vt] / [inspTime])
/// - **PCV**: [pip] (driving pressure above PEEP)
/// - **PSV**: [ps] (pressure support above PEEP) + [patientEffort]
@immutable
class VentParams {
  const VentParams({
    this.mode = VentMode.vcv,
    this.compliance = 50.0,
    this.resistance = 8.0,
    this.peep = 5.0,
    this.rr = 14,
    this.vt = 450,
    this.pip = 20.0,
    this.ps = 10.0,
    this.fio2 = 40,
    this.ieRatio = 2.0,
    this.patientEffort = 0.0,
    this.pHigh = 28.0,
    this.pLow = 0.0,
    this.tHigh = 4.5,
    this.tLow = 0.6,
    this.spontaneousRR = 0,
  });

  /// Factory with sensible defaults for a normal adult lung.
  factory VentParams.initial() => const VentParams();

  // ── Ventilator settings ────────────────────────────────────────────────

  /// Current ventilation mode (VCV, PCV, or PSV).
  final VentMode mode;

  /// Static lung compliance (mL/cmH₂O). Range: 10–100.
  ///
  /// Represents the lung's distensibility — how much volume is gained per
  /// unit of pressure. Low in ARDS/fibrosis (15–25), high in emphysema
  /// (80–100), normal ≈ 50.
  final double compliance;

  /// Total airway resistance (cmH₂O/L/s). Range: 3–40.
  ///
  /// Represents opposition to airflow through the airways. Normal ≈ 5–8.
  /// Elevated in bronchospasm (asthma 15–25) and COPD (15–20).
  /// Determines the resistive pressure component: P_res = Flow × R.
  final double resistance;

  /// Positive End-Expiratory Pressure (cmH₂O). Range: 0–25.
  ///
  /// Maintains alveolar recruitment at end-expiration, preventing
  /// atelectasis. Higher PEEP used in ARDS (10–18) to improve
  /// oxygenation; excessive PEEP risks hemodynamic compromise.
  final double peep;

  /// Respiratory rate (breaths per minute). Range: 6–40.
  ///
  /// Machine-set in VCV/PCV; patient-driven in PSV. Higher RR increases
  /// minute ventilation but reduces expiratory time, risking air trapping
  /// in obstructive disease.
  final int rr;

  /// Tidal volume target in mL (VCV mode). Range: 200–800.
  ///
  /// Lung-protective ventilation targets 6–8 mL/kg of predicted body
  /// weight. Exceeding 8 mL/kg PBW increases risk of ventilator-induced
  /// lung injury (VILI).
  final int vt;

  /// Peak Inspiratory Pressure above PEEP in cmH₂O (PCV mode). Range: 10–45.
  ///
  /// In PCV the ventilator delivers a square pressure wave; the achieved
  /// tidal volume depends on compliance: Vt ≈ C × (PIP − PEEP).
  final double pip;

  /// Pressure Support above PEEP in cmH₂O (PSV mode). Range: 5–30.
  ///
  /// Augments the patient's spontaneous effort. Weaning trials typically
  /// use PS 5–8 cmH₂O. Higher values compensate for weak respiratory
  /// muscles or high airway resistance.
  final double ps;

  /// Fraction of Inspired Oxygen (%). Range: 21–100.
  ///
  /// Room air = 21%. Target SpO₂ 92–96% in most patients. Prolonged
  /// FiO₂ > 60% risks oxygen toxicity. P/F ratio = PaO₂ / (FiO₂/100).
  final int fio2;

  /// Inspiratory-to-Expiratory ratio, expressed as 1:X. Range: 1.0–5.0.
  ///
  /// Normal 1:2. Obstructive disease benefits from longer expiration
  /// (1:3–1:4) to allow complete emptying. Inverse ratio (< 1:1) is
  /// rarely used outside specialised ARDS protocols.
  final double ieRatio;

  /// Patient's own inspiratory muscle effort in cmH₂O (PSV). Range: 0–10.
  ///
  /// Represents the negative pleural pressure generated by the diaphragm.
  /// Zero = fully passive; 5–10 = strong effort (e.g. during weaning).
  /// The engine subtracts this from alveolar pressure to drive flow.
  final double patientEffort;

  // ── APRV-specific parameters ──────────────────────────────────────────

  /// High pressure level in APRV mode (cmH₂O). Range: 15–40.
  /// Maintained for most of the cycle (T-high phase).
  final double pHigh;

  /// Low pressure level in APRV mode (cmH₂O). Range: 0–10.
  /// Brief release phase for CO₂ clearance (T-low phase).
  final double pLow;

  /// Duration of the high-pressure phase in APRV (seconds). Range: 2–8.
  final double tHigh;

  /// Duration of the release (low-pressure) phase in APRV (seconds).
  /// Range: 0.2–1.5. Typically 0.5–0.8 s.
  final double tLow;

  /// Spontaneous respiratory rate overlay in APRV (breaths/min).
  /// Range: 0–30. Represents small tidal breaths during P-high phase.
  final int spontaneousRR;

  // ── Derived values ─────────────────────────────────────────────────────

  /// RC time constant τ = R × C (seconds).
  ///
  /// Determines how quickly the lung fills/empties. After 3τ ≈ 95% of
  /// equilibrium volume is reached; after 5τ ≈ 99%. A long τ (high R
  /// and/or high C) requires longer expiratory time to avoid air trapping.
  double get tau => resistance * compliance / 1000.0;

  /// Total respiratory cycle time (seconds).
  /// APRV: T-high + T-low. Others: 60 / RR.
  double get totalCycleTime =>
      mode == VentMode.aprv ? tHigh + tLow : 60.0 / rr;

  /// Inspiratory time (seconds).
  /// APRV: T-high phase. Others: Ttotal / (1 + I:E).
  double get inspTime =>
      mode == VentMode.aprv ? tHigh : totalCycleTime / (1.0 + ieRatio);

  /// Expiratory time (seconds).
  /// APRV: T-low (release) phase. Others: Ttotal − Ti.
  double get expTime =>
      mode == VentMode.aprv ? tLow : totalCycleTime - inspTime;

  VentParams copyWith({
    VentMode? mode,
    double? compliance,
    double? resistance,
    double? peep,
    int? rr,
    int? vt,
    double? pip,
    double? ps,
    int? fio2,
    double? ieRatio,
    double? patientEffort,
    double? pHigh,
    double? pLow,
    double? tHigh,
    double? tLow,
    int? spontaneousRR,
  }) =>
      VentParams(
        mode: mode ?? this.mode,
        compliance: compliance ?? this.compliance,
        resistance: resistance ?? this.resistance,
        peep: peep ?? this.peep,
        rr: rr ?? this.rr,
        vt: vt ?? this.vt,
        pip: pip ?? this.pip,
        ps: ps ?? this.ps,
        fio2: fio2 ?? this.fio2,
        ieRatio: ieRatio ?? this.ieRatio,
        patientEffort: patientEffort ?? this.patientEffort,
        pHigh: pHigh ?? this.pHigh,
        pLow: pLow ?? this.pLow,
        tHigh: tHigh ?? this.tHigh,
        tLow: tLow ?? this.tLow,
        spontaneousRR: spontaneousRR ?? this.spontaneousRR,
      );
}

// ═══════════════════════════════════════════════════════════════════════════
// 2. PatientData — anthropometric data for IBW / protective Vt calculation
// ═══════════════════════════════════════════════════════════════════════════

/// Immutable patient demographic and anthropometric data.
///
/// Used to compute the Ideal Body Weight (IBW) and the protective tidal
/// volume range (6–8 mL/kg IBW) per the ARDSNet protocol.
@immutable
class PatientData {
  const PatientData({
    this.sex = Sex.male,
    this.heightCm = 170,
    this.weightKg = 70,
    this.age = 50,
  });

  /// Factory with sensible defaults for a 170 cm male, 70 kg, 50 y/o.
  factory PatientData.initial() => const PatientData();

  /// Biological sex — affects the IBW baseline constant.
  final Sex sex;

  /// Height in centimeters. Range: 140–210.
  final int heightCm;

  /// Actual body weight in kilograms. Range: 30–200.
  final int weightKg;

  /// Age in years. Range: 18–100.
  final int age;

  // ── Derived values ─────────────────────────────────────────────────────

  /// Ideal Body Weight (kg) using the ARDSNet / Devine formula.
  ///
  /// - Male:   IBW = 50.0 + 0.91 × (height_cm − 152.4)
  /// - Female: IBW = 45.5 + 0.91 × (height_cm − 152.4)
  double get ibw => sex == Sex.male
      ? 50.0 + 0.91 * (heightCm - 152.4)
      : 45.5 + 0.91 * (heightCm - 152.4);

  /// Body Mass Index (kg/m²) = weight / height².
  double get bmi => weightKg / math.pow(heightCm / 100.0, 2);

  /// Lower bound of protective tidal volume: 6 mL/kg IBW (mL).
  int get idealVt6 => (ibw * 6).round();

  /// Upper bound of protective tidal volume: 8 mL/kg IBW (mL).
  int get idealVt8 => (ibw * 8).round();

  PatientData copyWith({
    Sex? sex,
    int? heightCm,
    int? weightKg,
    int? age,
  }) =>
      PatientData(
        sex: sex ?? this.sex,
        heightCm: heightCm ?? this.heightCm,
        weightKg: weightKg ?? this.weightKg,
        age: age ?? this.age,
      );
}

// ═══════════════════════════════════════════════════════════════════════════
// 3. BreathSample — single time-domain data point
// ═══════════════════════════════════════════════════════════════════════════

/// A single instantaneous sample from the ventilator simulation.
///
/// The engine produces one of these every [EngineConstants.dt] seconds.
/// These are collected into the rolling waveform buffer and rendered
/// as pressure, flow, and volume curves on the UI.
@immutable
class BreathSample {
  const BreathSample({
    required this.pressure,
    required this.flow,
    required this.volume,
    required this.phase,
  });

  /// Factory for a zeroed sample at the start of simulation.
  factory BreathSample.initial() => const BreathSample(
        pressure: 0,
        flow: 0,
        volume: 0,
        phase: BreathPhase.expiration,
      );

  /// Airway pressure at this instant (cmH₂O).
  ///
  /// In VCV this rises during inspiration due to elastic + resistive
  /// components. In PCV it is held constant (square wave).
  final double pressure;

  /// Instantaneous gas flow (L/min).
  ///
  /// Positive = inspiratory (into the lungs).
  /// Negative = expiratory (out of the lungs).
  final double flow;

  /// Instantaneous lung volume above functional residual capacity (mL).
  ///
  /// Starts at 0 (FRC) at the beginning of inspiration and returns
  /// toward 0 during expiration. If incomplete emptying occurs,
  /// the residual volume represents trapped gas (auto-PEEP).
  final double volume;

  /// Current phase of the respiratory cycle at this sample.
  final BreathPhase phase;

  BreathSample copyWith({
    double? pressure,
    double? flow,
    double? volume,
    BreathPhase? phase,
  }) =>
      BreathSample(
        pressure: pressure ?? this.pressure,
        flow: flow ?? this.flow,
        volume: volume ?? this.volume,
        phase: phase ?? this.phase,
      );
}

// ═══════════════════════════════════════════════════════════════════════════
// 4. CycleMetrics — per-breath derived clinical measurements
// ═══════════════════════════════════════════════════════════════════════════

/// Summary metrics for a single completed breath cycle.
///
/// These values are "frozen" once per cycle (at the start of expiration)
/// and displayed on the monitor panel. They mirror what a real ICU
/// ventilator screen shows.
@immutable
class CycleMetrics {
  const CycleMetrics({
    required this.pip,
    required this.peep,
    required this.vte,
    required this.rr,
  });

  /// Factory with zero values for pre-simulation state.
  factory CycleMetrics.initial() => const CycleMetrics(
        pip: 0,
        peep: 0,
        vte: 0,
        rr: 0,
      );

  /// Peak Inspiratory Pressure (cmH₂O) — the highest pressure reached
  /// during the inspiratory phase. Alarm threshold typically 40 cmH₂O.
  final int pip;

  /// End-Expiratory Pressure (cmH₂O) — measured PEEP including any
  /// auto-PEEP component. Should approximate the set PEEP in the
  /// absence of air trapping.
  final int peep;

  /// Expired Tidal Volume (mL) — the volume actually exhaled by the
  /// patient. In VCV this should match the set Vt unless there is a
  /// leak or the pressure limit is reached.
  final int vte;

  /// Measured Respiratory Rate (breaths/min) — derived from the time
  /// between consecutive breath onsets. May differ from set RR in PSV
  /// where the patient controls the rate.
  final int rr;

  /// Minute Ventilation (L/min) = Vte × RR / 1000.
  ///
  /// Normal range 5–8 L/min. Primary determinant of CO₂ elimination.
  double get minuteVolume => (vte * rr) / 1000.0;

  CycleMetrics copyWith({
    int? pip,
    int? peep,
    int? vte,
    int? rr,
  }) =>
      CycleMetrics(
        pip: pip ?? this.pip,
        peep: peep ?? this.peep,
        vte: vte ?? this.vte,
        rr: rr ?? this.rr,
      );
}

// ═══════════════════════════════════════════════════════════════════════════
// 5. AbgInput — arterial blood gas input values
// ═══════════════════════════════════════════════════════════════════════════

/// Arterial blood gas (ABG) laboratory values entered by the learner.
///
/// These are the raw numbers from a blood gas analyser. The engine uses
/// them to determine acid-base status, oxygenation adequacy (P/F ratio),
/// and to suggest ventilator adjustments.
@immutable
class AbgInput {
  const AbgInput({
    this.ph = 7.40,
    this.pco2 = 40.0,
    this.hco3 = 24.0,
    this.pao2 = 90.0,
    this.sao2 = 97.0,
    this.lactato = 1.0,
  });

  /// Factory with textbook-normal ABG values.
  factory AbgInput.initial() => const AbgInput();

  /// Arterial pH. Normal: 7.35–7.45. Range: 6.80–7.80.
  ///
  /// < 7.35 = acidemia; > 7.45 = alkalemia. Extreme values (< 7.10 or
  /// > 7.60) are life-threatening.
  final double ph;

  /// Partial pressure of CO₂ in arterial blood (mmHg). Normal: 35–45.
  /// Range: 10–120.
  ///
  /// Regulated by alveolar ventilation. High PaCO₂ (hypercapnia) →
  /// respiratory acidosis; low PaCO₂ (hypocapnia) → respiratory alkalosis.
  final double pco2;

  /// Serum bicarbonate (mEq/L). Normal: 22–26. Range: 5–50.
  ///
  /// Metabolic component of acid-base. Low = metabolic acidosis
  /// (e.g. lactic acidosis, renal failure); high = metabolic alkalosis
  /// (e.g. vomiting, diuretic use).
  final double hco3;

  /// Partial pressure of O₂ in arterial blood (mmHg). Normal: 80–100.
  /// Range: 20–600.
  ///
  /// Primary measure of oxygenation. PaO₂ / FiO₂ < 300 defines ARDS.
  /// Values > 100 are normal on supplemental O₂.
  final double pao2;

  /// Arterial oxygen saturation (%). Normal: 95–100. Range: 50–100.
  ///
  /// Follows the oxyhemoglobin dissociation curve. SpO₂ < 90%
  /// corresponds to PaO₂ ≈ 60 mmHg (critical hypoxemia).
  final double sao2;

  /// Arterial lactate (mmol/L). Normal: < 2.0. Range: 0–30.
  ///
  /// Marker of tissue hypoperfusion / anaerobic metabolism.
  /// > 2 = elevated; > 4 = severe (associated with higher mortality
  /// in sepsis and shock).
  final double lactato;

  AbgInput copyWith({
    double? ph,
    double? pco2,
    double? hco3,
    double? pao2,
    double? sao2,
    double? lactato,
  }) =>
      AbgInput(
        ph: ph ?? this.ph,
        pco2: pco2 ?? this.pco2,
        hco3: hco3 ?? this.hco3,
        pao2: pao2 ?? this.pao2,
        sao2: sao2 ?? this.sao2,
        lactato: lactato ?? this.lactato,
      );
}

// ═══════════════════════════════════════════════════════════════════════════
// 6. AbgFinding — single interpretive finding from ABG analysis
// ═══════════════════════════════════════════════════════════════════════════

/// A single clinical finding derived from ABG interpretation.
///
/// Examples:
/// - (warning, "Acidose respiratória: PaCO₂ 55 mmHg")
/// - (danger, "Hipoxemia grave: PaO₂/FiO₂ = 85")
@immutable
class AbgFinding {
  const AbgFinding({
    required this.level,
    required this.text,
  });

  /// Severity of this finding (ok, info, warning, danger).
  final AlertLevel level;

  /// Human-readable description in Portuguese.
  final String text;

  AbgFinding copyWith({
    AlertLevel? level,
    String? text,
  }) =>
      AbgFinding(
        level: level ?? this.level,
        text: text ?? this.text,
      );
}

// ═══════════════════════════════════════════════════════════════════════════
// 7. AbgAction — suggested ventilator adjustment
// ═══════════════════════════════════════════════════════════════════════════

/// A specific ventilator adjustment recommended based on ABG analysis.
///
/// Actions are ordered by [priority] (0 = urgent, 1 = important,
/// 2 = optimisation) and include enough context for the learner to
/// understand *what* to change, *why*, and *where* on the ventilator.
@immutable
class AbgAction {
  const AbgAction({
    required this.priority,
    required this.icon,
    required this.param,
    required this.action,
    required this.reason,
    required this.where,
  });

  /// Urgency tier: 0 = life-threatening, 1 = clinically important,
  /// 2 = fine-tuning / optimisation.
  final int priority;

  /// Emoji or icon identifier for visual cue (e.g. "🔺", "⬇️", "⚠️").
  final String icon;

  /// The ventilator parameter to adjust (e.g. "RR", "PEEP", "FiO₂").
  final String param;

  /// What to do (e.g. "Aumentar de 14 para 18 rpm").
  final String action;

  /// Clinical rationale (e.g. "PaCO₂ elevada → aumentar ventilação
  /// alveolar para corrigir acidose respiratória").
  final String reason;

  /// Physical location on the ventilator interface where the
  /// adjustment is made (e.g. "Painel principal → RR").
  final String where;

  AbgAction copyWith({
    int? priority,
    String? icon,
    String? param,
    String? action,
    String? reason,
    String? where,
  }) =>
      AbgAction(
        priority: priority ?? this.priority,
        icon: icon ?? this.icon,
        param: param ?? this.param,
        action: action ?? this.action,
        reason: reason ?? this.reason,
        where: where ?? this.where,
      );
}

// ═══════════════════════════════════════════════════════════════════════════
// 8. AbgAnalysis — complete ABG interpretation result
// ═══════════════════════════════════════════════════════════════════════════

/// Complete output of the ABG analysis engine.
///
/// Contains the primary acid-base disorder, a list of clinical findings
/// (with severity), actionable ventilator adjustments, and key derived
/// metrics (P/F ratio, driving pressure, Vt/kg, etc.).
@immutable
class AbgAnalysis {
  const AbgAnalysis({
    required this.primaryDisorder,
    required this.findings,
    required this.actions,
    required this.pfRatio,
    required this.drivingPressure,
    required this.pplat,
    required this.vtPerKg,
    required this.minuteVolume,
    required this.alveolarVentilation,
  });

  /// Factory for an empty / pre-analysis state.
  factory AbgAnalysis.initial() => const AbgAnalysis(
        primaryDisorder: '',
        findings: [],
        actions: [],
        pfRatio: 0,
        drivingPressure: 0,
        pplat: 0,
        vtPerKg: 0,
        minuteVolume: 0,
        alveolarVentilation: 0,
      );

  /// Primary acid-base disorder label.
  ///
  /// Examples: "Acidose respiratória aguda", "Alcalose metabólica
  /// com compensação respiratória", "Distúrbio misto".
  final String primaryDisorder;

  /// Ordered list of interpretive findings (most severe first).
  final List<AbgFinding> findings;

  /// Prioritised list of suggested ventilator adjustments.
  final List<AbgAction> actions;

  /// PaO₂ / FiO₂ ratio — key metric for ARDS classification.
  ///
  /// - > 300: normal oxygenation
  /// - 200–300: mild ARDS
  /// - 100–200: moderate ARDS
  /// - < 100: severe ARDS
  final double pfRatio;

  /// Driving pressure = Pplateau − PEEP (cmH₂O).
  ///
  /// Strong predictor of mortality in ARDS. Target ≤ 15 cmH₂O.
  final double drivingPressure;

  /// Plateau pressure (cmH₂O) — reflects alveolar distending pressure.
  ///
  /// Target ≤ 30 cmH₂O to prevent ventilator-induced lung injury.
  final double pplat;

  /// Tidal volume normalised to predicted body weight (mL/kg PBW).
  ///
  /// Lung-protective range: 6–8 mL/kg PBW.
  final double vtPerKg;

  /// Minute ventilation (L/min) = Vt × RR / 1000.
  final double minuteVolume;

  /// Alveolar ventilation (L/min) = (Vt − deadSpace) × RR / 1000.
  ///
  /// Estimated dead space ≈ 2 mL/kg IBW. This is the effective
  /// ventilation that participates in gas exchange.
  final double alveolarVentilation;

  AbgAnalysis copyWith({
    String? primaryDisorder,
    List<AbgFinding>? findings,
    List<AbgAction>? actions,
    double? pfRatio,
    double? drivingPressure,
    double? pplat,
    double? vtPerKg,
    double? minuteVolume,
    double? alveolarVentilation,
  }) =>
      AbgAnalysis(
        primaryDisorder: primaryDisorder ?? this.primaryDisorder,
        findings: findings ?? this.findings,
        actions: actions ?? this.actions,
        pfRatio: pfRatio ?? this.pfRatio,
        drivingPressure: drivingPressure ?? this.drivingPressure,
        pplat: pplat ?? this.pplat,
        vtPerKg: vtPerKg ?? this.vtPerKg,
        minuteVolume: minuteVolume ?? this.minuteVolume,
        alveolarVentilation:
            alveolarVentilation ?? this.alveolarVentilation,
      );
}

// ═══════════════════════════════════════════════════════════════════════════
// 9. SimulationState — snapshot of the running simulation for the UI
// ═══════════════════════════════════════════════════════════════════════════

/// Immutable snapshot of the simulation state consumed by the UI layer.
///
/// Contains the rolling waveform buffers (pressure, flow, volume) ready
/// for rendering, the current write position, the active breath phase,
/// and the latest per-breath clinical metrics.
@immutable
class SimulationState {
  const SimulationState({
    required this.pressureData,
    required this.flowData,
    required this.volumeData,
    required this.currentIndex,
    required this.phase,
    required this.metrics,
  });

  /// Factory for the initial (blank-screen) state.
  ///
  /// Fills pressure with [peep] (baseline), flow and volume with 0.
  /// This ensures the waveform painters always have a full buffer to
  /// draw (avoids a blank canvas flash on reset).
  factory SimulationState.initial({double peep = 5.0}) {
    final bufSize = EngineConstants.bufferSize;
    return SimulationState(
      pressureData: List<double>.filled(bufSize, peep),
      flowData: List<double>.filled(bufSize, 0),
      volumeData: List<double>.filled(bufSize, 0),
      currentIndex: 0,
      phase: BreathPhase.expiration,
      metrics: const CycleMetrics(pip: 0, peep: 0, vte: 0, rr: 0),
    );
  }

  /// Rolling pressure waveform (cmH₂O).
  ///
  /// Length is up to [EngineConstants.bufferSize] samples. Earlier
  /// positions may be zero-padded before the first full buffer fill.
  final List<double> pressureData;

  /// Rolling flow waveform (L/min).
  final List<double> flowData;

  /// Rolling volume waveform (mL above FRC).
  final List<double> volumeData;

  /// Index of the most recent sample within the data lists.
  final int currentIndex;

  /// Current phase of the respiratory cycle (inspiration / expiration).
  final BreathPhase phase;

  /// Latest per-breath clinical metrics (PIP, PEEP, Vte, RR).
  ///
  /// Updated once per breath cycle when expiration begins. Before the
  /// first cycle completes, values are zero.
  final CycleMetrics metrics;

  SimulationState copyWith({
    List<double>? pressureData,
    List<double>? flowData,
    List<double>? volumeData,
    int? currentIndex,
    BreathPhase? phase,
    CycleMetrics? metrics,
  }) =>
      SimulationState(
        pressureData: pressureData ?? this.pressureData,
        flowData: flowData ?? this.flowData,
        volumeData: volumeData ?? this.volumeData,
        currentIndex: currentIndex ?? this.currentIndex,
        phase: phase ?? this.phase,
        metrics: metrics ?? this.metrics,
      );
}
